version: '3.7'

services:
  database_compass:
    image: postgres
    container_name: database_compass
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=nodejscompass
      - POSTGRES_DB=compass
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: nodejs-interview
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local